---
- name: Generating in-memory inventory
  hosts: localhost
  tasks:
    - import_tasks: tasks/generate_inventory.yaml
      when:
        - "'cloudstack_management' not in groups"

- name: "Building CloudStack {{ cs_version }}"
  hosts: cloudstack_management
  become_method: sudo
  roles:
    - role: build-cloudstack
      when:
        - build_cloudstack | bool

- name: "Installing CloudStack repository"
  hosts: environment_hosts
  become_method: sudo
  roles:
    - add-cloudstack-repository

- name: "Installing CloudStack management node"
  hosts: cloudstack_management
  become_method: sudo
  roles:
    - cloudstack-management

- name: Installing CloudStack hosts
  hosts: cluster_a1,cluster_a2,cluster_b1
  become_method: sudo
  roles:
    - cloudstack-kvm-hypervisor
  post_tasks:
    - name: Retrieving API Key
      run_once: true
      include_role:
        name: cloudstack-management
        apply:
          delegate_to: "{{ groups['cloudstack_management'][0] }}"
        tasks_from: retrieve-api-keys.yaml
      when:
        - configure_cloudstack | bool
    - name: Adding hosts to respective Clusters
      run_once: true
      delegate_to: localhost
      delegate_facts: true
      import_tasks: tasks/add_hosts_to_clusters.yml
      when:
        - configure_cloudstack | bool

