---
- name: Generating stack_uuid
  set_fact:
    stack_uuid: "{{ ('lab-cs-' + lab_environment + '-' + sp_version + '-' + cs_version + '-' + plugin_version) | to_uuid }}"
  when:
    - lab_environment is defined

- name: Generating a list of hosts that are part of the environment
  set_fact:
    environment_hosts: "{{ hostvars | dict2items(key_name='name', value_name='vars') | selectattr('vars.user_attributes.stack_uuid', 'eq', stack_uuid) | list }}"
  when:
    - stack_uuid is defined

- name: Debug hosts
  debug:
    msg: "{{ hostvars | dict2items(key_name='name', value_name='vars') }}"
    verbosity: 2

- name: Generating a list of hosts that are part of the environment
  set_fact:
    environment_hosts: "{{ hostvars | dict2items(key_name='name', value_name='vars') | selectattr('vars.user_attributes.env_type', 'eq', 'autotest') | list }}"
  when:
    - stack_uuid is not defined

- name: Generating cloudstack_management group
  add_host:
    hostname: "{{ host.name }}"
    groups:
      - cloudstack_management
      - environment_hosts
  loop: "{{ environment_hosts | selectattr('vars.user_attributes.role_name', 'eq', 'management') | list }}"
  loop_control:
    loop_var: host

- name: Printing cloudstack_management group
  debug:
    msg: "CloudStack management hosts: {{ groups['cloudstack_management'] }}"
    verbosity: 2

- name: Generating storpool_nodes group
  add_host:
    hostname: "{{ host.name }}"
    groups:
      - storpool_nodes
      - environment_hosts
  loop: "{{ environment_hosts | selectattr('vars.user_attributes.role_name', 'ne', 'management') | list }}"
  loop_control:
    loop_var: host

- name: Printing storpool_nodes group
  debug:
    msg: "StorPool server nodes: {{ groups['storpool_nodes'] }}"
    verbosity: 2

- name: Generating storpool_server_nodes group
  add_host:
    hostname: "{{ host.name }}"
    groups:
      - storpool_server_nodes
  loop: "{{ environment_hosts | selectattr('vars.user_attributes.role_name', 'ne', 'management') | selectattr('vars.storpool_services', 'contains', 'server') | list }}"
  loop_control:
    loop_var: host

- name: Printing storpool_server_nodes group
  debug:
    var: "{{ groups['storpool_server_nodes'] }}"
    verbosity: 2

- name: Generating cluster_* groups
  add_host:
    hostname: "{{ host.name }}"
    groups:
      - "cluster_{{ host.vars.user_attributes.cloudstack_cluster }}"
      - "{{ host.vars.user_attributes.role_name }}"
      - cloudstack_hypervisors
  loop: "{{ environment_hosts | selectattr('vars.user_attributes.role_name', 'ne', 'management') | list }}"
  loop_control:
    loop_var: host

