- name: Reconnecting Hosts
  command: "cmk reconnectHost id={{ host_id }}"
  loop: "{{ (hosts_list_result.stdout | from_json)['host'] | map(attribute='id') | list }}"
  loop_control:
    loop_var: host_id

- name: Listing present System VMs
  command: "cmk listSystemVms"
  register: system_vms_list_result

- name: Deleting old System VMs
  command: "cmk destroySystemVm id={{ system_vm_id }}"
  loop: "{{ (system_vms_list_result.stdout | from_json)['systemvm'] | map(attribute='id') | list }}"
  loop_control:
    loop_var: system_vm_id

- name: Listing present Routers
  command: "cmk listRouters"
  register: routers_list_result

- name: Deleting old System VMs
  command: "cmk destroyRouter id={{ router_id }}"
  loop: "{{ (routers_list_result.stdout | from_json)['router'] | map(attribute='id') | list }}"
  loop_control:
    loop_var: router_id

- name: Listing present Hosts
  command: "cmk listHosts"
  register: hosts_list_result
