---
- name: Adding MySQL community yum repo
  become: true
  ansible.builtin.yum_repository:
    name: mysql-community
    description: MySQL Community connectors
    baseurl: http://repo.mysql.com/yum/mysql-connectors-community/el/$releasever/$basearch/
    gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
    enabled: true
    gpgcheck: true


- name: Installing cloudstack-management  # noqa: package-latest
  become: true
  ansible.builtin.package:
    name:
      - cloudstack-management
      - mysql-server
    state: latest

- name: Creating MariaDB drop-in config for CloudStack
  become: true
  ansible.builtin.copy:
    src: cloudstack.cnf
    dest: /etc/my.cnf.d/
    mode: "0644"
  notify: Restart MySQL server

- name: Starting MySQL server
  become: true
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: true

- name: Checking if CloudStack database password is defined
  ansible.builtin.assert:
    that:
      - cloudstack_db_password is defined
      - cloudstack_db_password | length
    fail_msg: Please define a database password to be used by CloudStack database user

- name: Initializing CloudStack database
  become: true
  ansible.builtin.command:
    argv:
      - /usr/bin/cloudstack-setup-databases
      - "cloud:{{ cloudstack_db_password }}@localhost"
      - --deploy-as=root
    creates: "{{ cloudstack_init_db_shadow_file_path }}"
  notify: Setup CloudStack management

- name: Flushing handlers
  ansible.builtin.meta: flush_handlers
