---
- name: Creating storage directories
  become: true
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    mode: "0755"
  loop: "{{ nfs_export_directories }}"
  loop_control:
    loop_var: directory

- name: Exporting directories
  become: true
  ansible.builtin.import_role:
    name: geerlingguy.nfs
  vars:
    nfs_exports:
      - "/export  *(rw,async,no_root_squash,no_subtree_check)"
