- name: Checking if CloudStack agent user password is defined
  ansible.builtin.assert:
    that:
      - cloudstack_user_password is defined
    fail_msg: Please set a secure password for the CloudStack agent user

- name: Enabling Advanced virtualization repository  # noqa: package-latest
  become: true
  ansible.builtin.dnf:
    name: centos-release-advanced-virtualization
    state: latest
  when:
    - ansible_os_family == 'RedHat'
    - (ansible_distribution_major_version | int) >= 8

- name: Installing CloudStack agent packages  # noqa: package-latest
  become: true
  ansible.builtin.package:
    name:
      - cloudstack-agent
      - libvirt
    state: latest

- name: Creating CloudStack agent user
  become: true
  ansible.builtin.user:
    name: "{{ cloudstack_agent_username }}"
    password: "{{ cloudstack_user_password | password_hash('sha512') }}"
    shell: /bin/bash

- name: Allowing password-less sudo for CloudStack agent user
  become: true
  ansible.builtin.blockinfile:
    path: /etc/sudoers.d/cloudstack-user
    block: |
      {{ cloudstack_agent_username }} ALL=NOPASSWD: /usr/bin/cloudstack-setup-agent, /usr/share/cloudstack-common/scripts/util/keystore-setup, /usr/share/cloudstack-common/scripts/util/keystore-cert-import
      Defaults:{{ cloudstack_agent_username }} !requiretty
    create: true

- name: Configuring libvirt
  become: true
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    line: "{{ line.new }}"
    search_string: "{{ line.old }}"
  loop:
    - old: "listen_tls ="
      new: "listen_tls = 0"
    - old: "listen_tcp ="
      new: "listen_tcp = 1"
    - old: "tcp_port ="
      new: 'tcp_port = "16509"'
    - old: "mdns_adv ="
      new: "mdns_adv = 0"
  loop_control:
    loop_var: line
  notify:
    - Restart libvirtd

- name: Configuring SELinux
  become: true
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  when:
    - ansible_os_family == 'RedHat'

- name: Configuring network interfaces
  ansible.builtin.include_tasks: "configure_network_{{ ansible_os_family | lower }}.yml"
